"""Unit tests for the waiver-log block grammar (issue 028).

Fixture iron rule (PRD Testing Decisions): parsing tests for the PRODUCTION
format use verbatim production artifacts —
  - issue #306's ```waiver-log``` block (gh issue view 306 --json body
    archive, tests/fixtures/issue_306_batter.json)
  - the real waiver-log.md snapshot (tests/fixtures/waiver_log_2026-06-10.md)

New-grammar lines (7-field NEW / ACTION / CLOSE) have no production archive
pre-deploy by definition — those tests are CONTRACT fixtures derived from the
prompt output spec (prompt_fa_scan_pass2_batter.txt), built on real snapshot
content and real player names. Where possible, history lines are generated by
apply_waiver_log_block itself (writer output feeding the streak counter) so
tests cannot drift from the writer's real output format.
"""

import json
import re
from pathlib import Path

import pytest

from fa_scan import (
    _close_waiver_entry,
    _filter_waiver_log_by_group,
    apply_waiver_log_block,
    compute_replace_streak,
    inject_replace_streaks,
)

FIXTURES = Path(__file__).parent / "fixtures"

# Real positions for the four NEW rows in issue #306 (production block).
POSITIONS = {
    "Joc Pederson": "Util",
    "Kody Clemens": "1B,2B",
    "Curtis Mead": "1B,2B,3B",
    "Garrett Mitchell": "CF,RF",
}


@pytest.fixture()
def snapshot():
    return (FIXTURES / "waiver_log_2026-06-10.md").read_text(encoding="utf-8")


@pytest.fixture()
def issue_306_block():
    body = json.loads(
        (FIXTURES / "issue_306_batter.json").read_text(encoding="utf-8")
    )["body"]
    return body.split("```waiver-log")[1].split("```")[0].strip()


def _entry_of(content, name):
    """Extract one ### entry block (header through next header)."""
    m = re.search(
        rf"### {re.escape(name)} \([^)]+\)[^\n]*\n(?:(?!### |## ).*\n)*",
        content,
        re.MULTILINE,
    )
    return m.group(0) if m else None


# ── Backward compat: verbatim production block (pre-028 grammar) ──


class TestProductionBlockBackwardCompat:
    def test_block_applies_without_malformed_skips(self, snapshot, issue_306_block):
        content, modified, logs = apply_waiver_log_block(
            snapshot, issue_306_block, "06-11",
            position_lookup=POSITIONS, mlb_id_lookup=lambda n: None)
        assert modified
        assert not any("malformed" in msg for msg in logs)

    def test_update_lines_insert_dated_rows(self, snapshot, issue_306_block):
        content, _, _ = apply_waiver_log_block(
            snapshot, issue_306_block, "06-11",
            position_lookup=POSITIONS, mlb_id_lookup=lambda n: None)
        # Verbatim production UPDATE summary lands as a dated history line.
        assert ("- 06-11：14d OPS .887 / 3HR；PA-TG 2.36 上場有限觸發 2.5 "
                "遠未達；12% rising +2；持續觀察（fa_scan）") in content
        smith = _entry_of(content, "Cam Smith")
        assert "- 06-11：⚡ K% 25.9 + OPS .812 穩健連 7 天" in smith

    def test_old_6_field_new_creates_entry_without_vs_line(
            self, snapshot, issue_306_block):
        # Carve Curtis Mead's auto-closed entry out of the real snapshot so
        # the verbatim production NEW row exercises the create path.
        closed = _entry_of(snapshot, "Curtis Mead")
        assert closed is not None
        carved = snapshot.replace(closed, "")
        line = next(ln for ln in issue_306_block.split("\n")
                    if ln.startswith("NEW|Curtis Mead"))
        content, modified, _ = apply_waiver_log_block(
            carved, line, "06-11",
            position_lookup=POSITIONS, mlb_id_lookup=lambda n: 999)
        assert modified
        entry = _entry_of(content, "Curtis Mead")
        assert entry.startswith(
            "### Curtis Mead (WSH, 1B,2B,3B) [mlb_id:999] — 觀察中")
        assert "觸發：BBE ≥150 + xwOBA 維持 P90+" in entry
        assert "vs：" not in entry  # 6-field row has no vs column
        # New FA entries land inside 觀察中, before 隊上觀察.
        assert content.index("### Curtis Mead") < content.index("## 隊上觀察")

    def test_new_for_existing_player_falls_back_to_update(
            self, snapshot, issue_306_block):
        # Garrett Mitchell already has a 觀察中 entry in the snapshot — the
        # production NEW row must append a dated line, not a second entry.
        line = next(ln for ln in issue_306_block.split("\n")
                    if ln.startswith("NEW|Garrett Mitchell"))
        content, modified, _ = apply_waiver_log_block(
            snapshot, line, "06-11",
            position_lookup=POSITIONS, mlb_id_lookup=lambda n: None)
        assert modified
        assert content.count("### Garrett Mitchell") == 1
        assert "- 06-11：Season P70/P95/P95/P80 power 結構強" in _entry_of(
            content, "Garrett Mitchell")


# ── New grammar: 7-field NEW with vs column (contract per prompt spec) ──


class TestNewVsColumn:
    def test_7_field_new_writes_vs_line(self, snapshot):
        carved = snapshot.replace(_entry_of(snapshot, "Curtis Mead"), "")
        line = ("NEW|Curtis Mead|WSH||BBE ≥150 + xwOBA 維持 P90+ → 升級取代"
                "|Manny Machado|Season P95/P95/P70/P70 頂級但單年 breakout 風險")
        content, _, _ = apply_waiver_log_block(
            carved, line, "06-11",
            position_lookup=POSITIONS, mlb_id_lookup=lambda n: 999)
        entry = _entry_of(content, "Curtis Mead")
        lines = entry.split("\n")
        assert lines[1].startswith("觸發：")
        assert lines[2] == "vs：Manny Machado"
        assert lines[3].startswith("- 06-11：Season P95/P95/P70/P70")

    def test_7_field_new_empty_vs_omits_vs_line(self, snapshot):
        carved = snapshot.replace(_entry_of(snapshot, "Curtis Mead"), "")
        line = ("NEW|Curtis Mead|WSH||BBE ≥150 觀察||Season P95 頂級")
        content, _, _ = apply_waiver_log_block(
            carved, line, "06-11",
            position_lookup=POSITIONS, mlb_id_lookup=lambda n: None)
        entry = _entry_of(content, "Curtis Mead")
        assert "vs：" not in entry
        assert "- 06-11：Season P95 頂級（fa_scan）" in entry


# ── New grammar: ACTION lines ──


class TestActionLines:
    def test_action_annotates_same_block_update(self, snapshot):
        block = ("UPDATE|Cam Smith|⚡ K% 25.9 + OPS .812 穩健連 7 天\n"
                 "ACTION|Cam Smith|取代|Jarren Duran")
        content, modified, _ = apply_waiver_log_block(
            snapshot, block, "06-11", mlb_id_lookup=lambda n: None)
        assert modified
        assert ("- 06-11：[取代→Jarren Duran] ⚡ K% 25.9 + OPS .812 穩健連 7 天"
                "（fa_scan）") in _entry_of(content, "Cam Smith")

    def test_action_annotates_same_block_new(self, snapshot):
        carved = snapshot.replace(_entry_of(snapshot, "Curtis Mead"), "")
        block = ("NEW|Curtis Mead|WSH||立即行動|Ozzie Albies|Season 頂級\n"
                 "ACTION|Curtis Mead|立即取代|Ozzie Albies")
        content, _, _ = apply_waiver_log_block(
            carved, block, "06-11",
            position_lookup=POSITIONS, mlb_id_lookup=lambda n: None)
        entry = _entry_of(content, "Curtis Mead")
        assert "- 06-11：[立即取代→Ozzie Albies] Season 頂級（fa_scan）" in entry

    def test_standalone_action_inserts_day_line(self, snapshot):
        block = "ACTION|Paul Goldschmidt|立即取代|Luis Arraez"
        content, modified, logs = apply_waiver_log_block(
            snapshot, block, "06-11", mlb_id_lookup=lambda n: None)
        assert modified
        assert any("ACTION Paul Goldschmidt (standalone)" in m for m in logs)
        assert ("- 06-11：[立即取代→Luis Arraez] 取代判斷（fa_scan）"
                in _entry_of(content, "Paul Goldschmidt"))

    def test_standalone_action_unknown_player_skipped(self, snapshot):
        block = "ACTION|Nobody Nowhere|取代|Luis Arraez"
        content, modified, logs = apply_waiver_log_block(
            snapshot, block, "06-11", mlb_id_lookup=lambda n: None)
        assert not modified
        assert content == snapshot
        assert any("SKIP ACTION Nobody Nowhere" in m for m in logs)

    def test_action_with_invalid_type_skipped(self, snapshot):
        block = ("UPDATE|Cam Smith|摘要文字\n"
                 "ACTION|Cam Smith|觀察|Jarren Duran")
        content, _, logs = apply_waiver_log_block(
            snapshot, block, "06-11", mlb_id_lookup=lambda n: None)
        assert any("SKIP malformed ACTION" in m for m in logs)
        assert "[觀察→" not in content
        # the UPDATE itself still lands, unannotated
        assert "- 06-11：摘要文字（fa_scan）" in _entry_of(content, "Cam Smith")


# ── New grammar: CLOSE lines ──


class TestCloseLines:
    def test_close_moves_entry_with_full_history(self, snapshot):
        before = _entry_of(snapshot, "TJ Rumfield")
        n_history = len(re.findall(r"^- \d{2}-\d{2}：", before, re.MULTILINE))
        assert n_history > 10  # real entry has weeks of history

        block = "CLOSE|TJ Rumfield|觸發長期未達且 14d 品質下滑"
        content, modified, logs = apply_waiver_log_block(
            snapshot, block, "06-11", mlb_id_lookup=lambda n: None)
        assert modified
        assert any(m == "CLOSE TJ Rumfield" for m in logs)

        watch_section = content.split("## 隊上觀察")[0]
        assert "### TJ Rumfield" not in watch_section

        closed_section = content.split("## 已結案")[1]
        entry = _entry_of(closed_section, "TJ Rumfield")
        assert "— 已結案（fa_scan CLOSE）" in entry.split("\n")[0]
        assert "- 06-11：[結案] 觸發長期未達且 14d 品質下滑（fa_scan）" in entry
        # Full history preserved (+1 for the closing line itself).
        assert len(re.findall(r"^- \d{2}-\d{2}：", entry,
                              re.MULTILINE)) == n_history + 1

    def test_close_inserts_at_top_of_closed_section(self, snapshot):
        block = "CLOSE|TJ Rumfield|理由"
        content, _, _ = apply_waiver_log_block(
            snapshot, block, "06-11", mlb_id_lookup=lambda n: None)
        closed_section = content.split("## 已結案")[1]
        first_header = re.search(r"^### .*$", closed_section, re.MULTILINE)
        assert "TJ Rumfield" in first_header.group(0)

    def test_same_block_update_lands_before_close(self, snapshot):
        block = ("UPDATE|Gavin Sheets|14d OPS .488 持續下滑\n"
                 "CLOSE|Gavin Sheets|B-plan 弱化結構確認")
        content, _, _ = apply_waiver_log_block(
            snapshot, block, "06-11", mlb_id_lookup=lambda n: None)
        closed_section = content.split("## 已結案")[1]
        entry = _entry_of(closed_section, "Gavin Sheets")
        assert "- 06-11：14d OPS .488 持續下滑（fa_scan）" in entry
        assert "- 06-11：[結案] B-plan 弱化結構確認（fa_scan）" in entry

    def test_close_does_not_touch_team_watch_section(self, snapshot):
        # Ryan Jeffers lives under 隊上觀察, not 觀察中 — CLOSE must no-op.
        block = "CLOSE|Ryan Jeffers|傷情結束"
        content, modified, logs = apply_waiver_log_block(
            snapshot, block, "06-11", mlb_id_lookup=lambda n: None)
        assert not modified
        assert content == snapshot
        assert any("SKIP CLOSE Ryan Jeffers" in m for m in logs)

    def test_close_missing_player_no_change(self, snapshot):
        content, modified, logs = apply_waiver_log_block(
            snapshot, "CLOSE|Nobody Nowhere|x", "06-11",
            mlb_id_lookup=lambda n: None)
        assert not modified
        assert content == snapshot

    def test_close_condition_pass_skipped(self, snapshot):
        # Derive a 條件 Pass header from the real TJ Rumfield entry.
        marked = snapshot.replace(
            "### TJ Rumfield (COL, 1B) [mlb_id:681198] — 觀察中",
            "### TJ Rumfield (COL, 1B) [mlb_id:681198] — 條件 Pass")
        content, modified, _ = apply_waiver_log_block(
            marked, "CLOSE|TJ Rumfield|理由", "06-11",
            mlb_id_lookup=lambda n: None)
        assert not modified
        assert content == marked

    def test_close_helper_requires_closed_marker(self, snapshot):
        no_marker = snapshot.split("## 已結案")[0]
        content, moved = _close_waiver_entry(
            no_marker, "TJ Rumfield", "06-11", "理由")
        assert not moved
        assert content == no_marker


# ── Replace-streak counter (writer output feeds the counter — no
#    hand-written history lines) ──


def _apply_days(snapshot, blocks_by_date):
    content = snapshot
    for short_date, block in blocks_by_date:
        content, _, _ = apply_waiver_log_block(
            content, block, short_date, mlb_id_lookup=lambda n: None)
    return content


class TestReplaceStreak:
    def test_zero_streak_on_real_unannotated_entry(self, snapshot):
        entry = _entry_of(snapshot, "Cam Smith")
        assert compute_replace_streak(entry) == (0, None, None)

    def test_consecutive_action_days_accumulate(self, snapshot):
        content = _apply_days(snapshot, [
            ("06-11", "UPDATE|Cam Smith|摘要一\nACTION|Cam Smith|取代|Jarren Duran"),
            ("06-12", "UPDATE|Cam Smith|摘要二\nACTION|Cam Smith|立即取代|Jarren Duran"),
        ])
        streak, start, vs = compute_replace_streak(_entry_of(content, "Cam Smith"))
        assert (streak, start, vs) == (2, "06-11", "Jarren Duran")

    def test_unannotated_day_breaks_streak(self, snapshot):
        content = _apply_days(snapshot, [
            ("06-11", "UPDATE|Cam Smith|摘要一\nACTION|Cam Smith|取代|Jarren Duran"),
            ("06-12", "UPDATE|Cam Smith|摘要二"),  # no ACTION → streak resets
        ])
        assert compute_replace_streak(
            _entry_of(content, "Cam Smith")) == (0, None, None)

    def test_vs_taken_from_most_recent_annotation(self, snapshot):
        content = _apply_days(snapshot, [
            ("06-11", "UPDATE|J.P. Crawford|摘要\nACTION|J.P. Crawford|立即取代|Dansby Swanson"),
            ("06-12", "UPDATE|J.P. Crawford|摘要\nACTION|J.P. Crawford|立即取代|Luis Arraez"),
        ])
        streak, start, vs = compute_replace_streak(
            _entry_of(content, "J.P. Crawford"))
        assert (streak, start, vs) == (2, "06-11", "Luis Arraez")


# ── Payload injection ──


class TestInjectReplaceStreaks:
    def _filtered_watch_section(self, content):
        section = content.split("## 觀察中")[1].split("## 隊上觀察")[0]
        return _filter_waiver_log_by_group(section, "batter")

    def test_no_injection_without_streak(self, snapshot):
        filtered = self._filtered_watch_section(snapshot)
        assert inject_replace_streaks(filtered) == filtered

    def test_injects_derived_line_after_header(self, snapshot):
        content = _apply_days(snapshot, [
            ("06-11", "UPDATE|Cam Smith|摘要一\nACTION|Cam Smith|取代|Jarren Duran"),
            ("06-12", "UPDATE|Cam Smith|摘要二\nACTION|Cam Smith|取代|Jarren Duran"),
        ])
        injected = inject_replace_streaks(self._filtered_watch_section(content))
        entry = _entry_of(injected, "Cam Smith")
        assert entry.split("\n")[1] == (
            "[機械計數] 已連續推薦取代 2 個掃描日（自 06-11 起，vs Jarren Duran）")
        # Other entries untouched.
        assert "[機械計數]" not in _entry_of(injected, "Paul Goldschmidt")
